export const GALLERY_LIST_MOCKUP = [
  {
    id: 0,
    title: "브리츠(Britz) 웹 리뉴얼 디자인",
    image: "https://picsum.photos/seed/goyo1/600/800",
    tags: ["김OO 학생", "UI/UX"],
    likeCount: 128,
  },
  {
    id: 1,
    title: "미니멀리즘 가구 브랜드 'MODU' 브랜딩",
    image: "https://picsum.photos/seed/goyo2/600/800",
    tags: ["이OO 학생", "BX"],
    likeCount: 85,
  },
  {
    id: 2,
    title: "지속 가능한 패키지 디자인 제안",
    image: "https://picsum.photos/seed/goyo3/600/800",
    tags: ["박OO 학생", "Package"],
    likeCount: 42,
  },
  {
    id: 3,
    title: "전시회 '고요의 밤' 포스터 디자인",
    image: "https://picsum.photos/seed/goyo4/600/800",
    tags: ["최OO 학생", "Graphic"],
    likeCount: 214,
  },
  {
    id: 4,
    title: "비전공자를 위한 금융 앱 서비스 기획",
    image: "https://picsum.photos/seed/goyo5/600/800",
    tags: ["정OO 학생", "App"],
    likeCount: 67,
  },
  {
    id: 5,
    title: "전통주 브랜드 '달빛' 리브랜딩 프로젝트",
    image: "https://picsum.photos/seed/goyo6/600/800",
    tags: ["한OO 학생", "BX"],
    likeCount: 156,
  },
  {
    id: 6,
    title: "식물 집사를 위한 IoT 서비스 인터페이스",
    image: "https://picsum.photos/seed/goyo7/600/800",
    tags: ["강OO 학생", "UI/UX"],
    likeCount: 92,
  },
  {
    id: 7,
    title: "타이포그래피를 활용한 실험적 웹 포트폴리오",
    image: "https://picsum.photos/seed/goyo8/600/800",
    tags: ["임OO 학생", "Web"],
    likeCount: 110,
  },
  {
    id: 8,
    title: "반려견 산책 커뮤니티 '멍냥' 앱 디자인",
    image: "https://picsum.photos/seed/goyo9/600/800",
    tags: ["송OO 학생", "App"],
    likeCount: 320,
  },
  {
    id: 9,
    title: "독립 출판물 '성장의 기록' 북 커버 디자인",
    image: "https://picsum.photos/seed/goyo10/600/800",
    tags: ["윤OO 학생", "Print"],
    likeCount: 54,
  },
  {
    id: 10,
    title: "친환경 화장품 라벨 및 아이덴티티",
    image: "https://picsum.photos/seed/goyo11/600/800",
    tags: ["오OO 학생", "BX"],
    likeCount: 88,
  },
  {
    id: 11,
    title: "공간 큐레이션 서비스 웹 플랫폼 디자인",
    image: "https://picsum.photos/seed/goyo12/600/800",
    tags: ["권OO 학생", "Web"],
    likeCount: 73,
  },
];
